# Generated by Django 6.0.3 on 2026-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('panding', 'PANDING'), ('fullfilled', 'FULLFILLED'), ('REJECTED', 'rejected')], default='panding', max_length=10),
        ),
    ]
