# Generated by Django 6.0.3 on 2026-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_description_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('panding', 'PANDING'), ('fullfilled', 'FULLFILLED'), ('rejected', 'REJECTED')], default='panding', max_length=10),
        ),
    ]
